### PR TITLE
golint ci

### PR DESCRIPTION
**Pull request by Uchencho**
Testing golint ci

### CODE REVIEW

**Comment by Uchencho** [comment]
@Oppodelldog I have changed the repo from private to pubic, hence the error message has changed. Kindly take a look

**Comment by Oppodelldog** [comment]
The error might come.e from non matching case sensitive import in okra.go.

https://github.com/Uchencho/OkraGo/blob/ba2f9aa7da059cb433d6ef67fe11e5cabd989ce8/okra.go#L11

Repo is named "OkraGo", import refers to "okraGo".

**Comment by Uchencho** [comment]
I have added more struct responses but it seems some of their products are down so they return either 500 or 400. 

About tests, I have read extensively on mocking, I would like to ask how it applies here. My understanding of mocking is to prevent us from hitting the okra API repeatedly when running tests, but isn't that what I am testing for? Or am I testing that I can handle what comes back?

**Comment by Oppodelldog** [comment]
Yes, mocking will help us to not depend on the sandbox. Surely the client is supposed to communicate with okra api so why not directly going against it? Simultating the api is also error prone, if you implement a wrong simulation of okra api in tests, your client implementation will also be wrong, so where is the benefit?

Lets go one step back and try to find a test strategy in general, ask a simple question:
What is teh software under test doing?

The software is providing a library with an API that wraps okra API calls

So in detail it is:
* taking user input
* transform the user input into okra request
* sends a http request (decorated with authentication headers, maybe content type header and request as payload) to a specific api path
* checking the response for valid status code, decorated error on any failure
* deserializing the server response into a go struct 
* passing back struct and possibly and error to the user

I hope I covered all details of the data processing.
So now you can decide how to put all those details into tests.
Many details will be tested and raise some complexity to cover all the edge cases.

"Where are the seams you can cut and do some testing?"
This is a bit general thinking, but it might help you in future to decide how to write tests and later how to write code to have easier testing.

I like to show you the following picture, no need to read the article, but the picture nicely represents software components and how the seams could be used for testing.
https://martinfowler.com/tags/testing.html
In the right middle you can also find a typical API client and how it could be tested against an external service.  It is here proposed to use a technique called "contract testing".

In another article you can find the test pyramid which shall lead to a maintainable code.
https://martinfowler.com/articles/practical-test-pyramid.html
I am not sure how it scales on library level we are currently talking about, but I want to show up, that there is a difference in unit tests, integration tests and end to end tests. 

Calling okra sandbox, the real target system, would give a good proof that the client works in real life.
On the other hand it is not made for detailed testing, maybe in writing those tests you cannot simulate all scenarios that are supposed to happen. If I remember well the okra docs have an error section, how will you have to can the api to get all those different errors?
If it is possible to cover everything and still having readable test code it would be a good approach to use the api directly. Then the only downside then would be that you require an internet connection to call the api. To me this is the best argument to not call the real api directly in tests. Having connection issues will let the tests fail and I like to have stable tests.

In professional situations you will also not find those kind of tests, only if it is really intended to test services integrative or from end to end and both parties agree to do that.

So in general you will find so called contract testing - while contract means that both sides implementation relies on the documentation.

Now if you wanted to do the contract testing you could use mocking to mock the okra API.
Which means to simulate the API to test the details.

I would say from the tests (definition what is tested, what are the inputs, what is transmitted, returned and so on) it is the same regardless of if you mock the api or not.
You can try implement the tests with the real api, the benefit would be that you have all test definitions. It you are having trouble then or if the api is not reachable from travis or where ever the tests are run from, you could still introduce the mock as we discussed earlier using the httptest package.

regarding the error codes you are currently receiving:
500 means "internal server error" read the response content to find out more.
400 means "bad request", so there was something wrong with the request you have sent.
I cannot give any details, you should find an answer in the okra docs. If the contract/docs are not giving an answer, you could get into contact with them, asking for help.

I hope I could lead you a bit into a direction to have good test definitions first, before start writing the test.   Some developers use a technique called "TDD - test driven development" They write a test which fails, then write the first line of real code, then write a more detailed test and so on.
In the end regardless of if you write code or tests first it is best practise to have test that cover the code in a deterministic way, this will help making adjustements, extensions and so on.

**Pull request closed without merging**
